name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  trigger_argocd_builder_action:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create issue using REST API
        run: |
          message=${{ github.head_ref }}.${{ github.sha }}
          echo Head Ref and Hash: $message
          curl --request POST \
          --url https://api.github.com/repos/gajananan/argo-github-action/dispatches \
          --header 'authorization: Bearer ${{ secrets.ARGOCD_BUILDER_ACTION_SECRET }}' \
          --header "Accept: application/vnd.github.v3+json" \
          --data "{\"event_type\":\"webhook\", \"client_payload\": {\"commit_hash\": \"$message\", \"argo-config\": \"https://github.com/gajananan/akmebank-config\" }}" 
